# Generated by Django 5.1.7 on 2025-03-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Audience Name')),
                ('locations', models.TextField(default='United States', max_length=50)),
                ('age', models.IntegerField(default=18, max_length=2, verbose_name='18')),
                ('language', models.TextField(default='English', max_length=15, verbose_name='English')),
                ('interest', models.CharField(choices=[('cars', 'Cars'), ('motorcycles', 'Motorcycles'), ('tecnologies', 'Tecnologies'), ('men', 'Men'), ('women', 'Women'), ('books', 'Books'), ('all', 'All')], default='all', max_length=15, verbose_name='Interest Options')),
                ('activated', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Activation Status')),
            ],
        ),
        migrations.CreateModel(
            name='Branchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Branch Name')),
                ('monthly_budget', models.FloatField(verbose_name='0.00')),
                ('daily_budget', models.FloatField(verbose_name='0.00')),
                ('pixel', models.TextField(max_length=150, verbose_name='Pixel ID')),
                ('activated', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Activation Status')),
                ('instagram', models.TextField(max_length=100, verbose_name='Instagram URL')),
                ('facebook', models.TextField(max_length=100, verbose_name='Facebook URL')),
                ('website', models.TextField(max_length=100, verbose_name='Website URL')),
            ],
        ),
        migrations.CreateModel(
            name='Positionings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Audience Name')),
                ('facebook', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Facebook Enabled')),
                ('instagram', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, verbose_name='Instagram Enabled')),
                ('devices', models.CharField(choices=[('Mobile', 'Mobiles'), ('PCs', 'Pcs'), ('All', 'All')], default='All', max_length=10, verbose_name='Device Option')),
                ('activated', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Activation Status')),
            ],
        ),
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Campaign Name')),
                ('activated', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Activation Status')),
                ('daily_budget', models.FloatField(verbose_name='0.00')),
                ('dayparting', models.BooleanField(default=False, verbose_name='Dayparting Enabled')),
                ('dayparting_hours', models.JSONField(blank=True, null=True, verbose_name='Dayparting Hours')),
                ('objetive_of_the_compaign', models.CharField(choices=[('Leads', 'Leads'), ('Traffic', 'Traffic'), ('Sales', 'Sales')], default='Sales', max_length=10, verbose_name='Choose a campaign Objetve')),
                ('audience_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.audiences', verbose_name='Choose the Audience')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.branchs', verbose_name='Choose the Branch')),
                ('positioning_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.positionings', verbose_name='Choose the Positions')),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Campaign Name')),
                ('format', models.CharField(choices=[('Video', 'Video'), ('Image', 'Image')], default='Image', max_length=10, verbose_name='Choose the format')),
                ('destination', models.TextField(max_length=200)),
                ('activated', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Activation Status')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaigns', verbose_name='Choose the Campaign')),
            ],
        ),
    ]
